Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['let', 'it', 'describe', 'context', 'specify']
  Exclude:
    - proforma-extended-evaluator.gemspec

Metrics/MethodLength:
  Max: 25

AllCops:
  TargetRubyVersion: 2.3
